### ISSUE TITLE
IReactorChamber is back

### ISSUE THREAD

**Issue by Speiger** [World-Control-Team/World-Control#1]
https://github.com/World-Control-Team/World-Control/blob/master/src/main/java/worldcontrolteam/worldcontrol/crossmod/industrialcraft2/IC2ReactorHeat.java#L19

Please update the API and fix that. It would make compat from the begining way easier (IC2C)

**Comment by Speiger** [comment]
Here another one:
https://github.com/World-Control-Team/World-Control/blob/0ff49095342b505aaec32c2d197c914a11545053/src/main/java/worldcontrolteam/worldcontrol/crossmod/industrialcraft2/items/IC2ReactorCard.java#L36

Classic will have fluid reactors... So yeah (Make the is FluidReactor Check)

**Comment by dmf444** [comment]
@Speiger do you use a different mod id from ic2?

**Comment by Speiger** [comment]
@dmf444 i have to modIDs "IC2" & "IC2-Classic-Spmod"
But IC2 is the Main ModID...
But these suggestions are not only for IC2C support its for general Reactor Support. Because as soon someone else makes a reactor using the IC2 API it would not been detected or crash...
Edit: I had to talk a lot to the IC2 Team to get IReactorChamber back and also to not limit IReactor to a TileEntity....

**Comment by dmf444** [comment]
I need to check a few things out, just to confirm with reactors. They were causing me a lot of grief the other day. So long as it works, I can't complain. 

Does ic2c's mod Id have to be present for the steam generator? If so, I may just make it a separate mod integration.

**Comment by Speiger** [comment]
It has a fully implemented SteamReactor (in 1.7.10, 1.9 did not reach that far in the progress yet but it will be implemented before release). It supports everything in the ReactorAPI (it was already working with the old NC Code) but if you need more (like tankInfo) there is API file for that...
