### ISSUE TITLE
Howler alarm don't stop if switched off

### ISSUE THREAD

**Issue by GeneralDexter** [World-Control-Team/World-Control#13]
Hey WorldControl-Team

I play version 1.10.2 worldcontrol 1.0.1a. Firstly thank you very much for your work.

Issue: The howler alarm does not turn off after the input signal is interrupted by a switch. Is that wanted?

and...
Is it possible to change the time between to alarms? I want to add new sounds, but with a pause (i think 2 ticks) between it's difficult. Continous alarms has to be very long tracks and you can't stop it (as mentioned above). I can help you modifing alarm sounds with a pause at the end of each track. Thanks

**Comment by dmf444** [comment]
This is done with MC audio code, so I've no idea how to insta-stop it.
