### ISSUE TITLE
Remote Controller does not show up

### ISSUE THREAD

**Issue by nightmarezzx** [World-Control-Team/World-Control#22]
In creative inventory, the block is invisible, able to place it, but still invisible

**Comment by nightmarezzx** [comment]
Seems like there are a lot of problems in this very nice mod. Are you guys still working on it in 1.12.2?

**Comment by dmf444** [comment]
Yes

**Comment by nightmarezzx** [comment]
Good to here, thank you!

**Comment by dmf444** [comment]
This is fixed in dev
