### ISSUE TITLE
Editing a thermal monitor causes sponeforge to throw a Exception

### ISSUE THREAD

**Issue by MythTheWolf** [World-Control-Team/World-Control#25]
Running spongeforge 1.12.2-2768-7.1.5, and when you edit a thermal monitor, sponeforge panics and kicks you from the game. Seems to be trying to run sponge API on the main thread. https://gist.github.com/MythTheWolf/65d2e13f809b6516a435d9fe7c45c08d#file-latest-log-L2284

**Comment by MythTheWolf** [comment]
I'll make a fork and see if I can fix main thread API calls, and PR if I can get a fix. 
I was trying to so yesterday, but had some NMS dependency issues

**Comment by MythTheWolf** [comment]
UPDATE: I have since removed spongeforge due to some AE2 incompatibility, so WC might run. However, I am sure that packs with sponge will still have issues. I have changed the update method to run on a task, so that MC itself will call it on the main thread, will test soon.

**Comment by dmf444** [comment]
No idea why the worldserver hangs, this is a simple call to notify world of block updates. ATM, I'd have no real fix for it, and I'm not comfortable running a thread for a simple block update.

**Comment by dmf444** [comment]
Closed by stale & SpongeForge.
