### ISSUE TITLE
Custom howler alarm sounds doesnt work

### ISSUE THREAD

**Issue by ghost** [World-Control-Team/World-Control#37]
I tried this exactly and it didnt work: https://github.com/World-Control-Team/World-Control/wiki/Adding-Custom-Sounds-to-the-Howler-Alarm

Please help what should i do? Is it no longer possible?

**Comment by xbony2** [comment]
You probably did something wrong. Please share your sounds.json file, since that's usually what people mess up with.

**Comment by ghost** [comment]
{
    "alarm-nuclearalarmsiren": {"category": "master","sounds": [{"name": "worldcontrol:alarm-nuclearalarmsiren","stream": true}]}
}



file was modified in WCalarms/assets/worldcontrol/sounds.json

**Comment by xbony2** [comment]
I think the JSON file is correct. Did you add the .ogg file and add the custom alarm to the config while changing UseCustomSounds to true? Please show me your config file.

**Comment by ghost** [comment]
Yes i added sound file called alarm-nuclearalarmsiren.ogg


Yes i added true to usecustomsounds. I cant copy the file here cuz i am not on pc right now

**Comment by ghost** [comment]
# Configuration file

general {
    I:SMPmaxAlarmRange=256
    I:alarmRange=64
    S:howlerAlarmSounds <
        default
        sci-fi
        nuclearalarmsiren
     >
    I:maxAlarmRange=128
    I:remoteMonitorPowerUseIC2=1
    I:ticksBetweenHowlerSound=2
    B:useCustomSounds=true
}

**Comment by xbony2** [comment]
Is that the exact config file? I would try to delete it to regenerate it, I think it might be the issue. And then add nuclearalarmsiren.

**Comment by ghost** [comment]
Yes it gives me this config file everytime i delete it. Is it a bug? I downloaded latest version of worldcontrol

**Comment by xbony2** [comment]
I don't think so. I can't see what's wrong but other people have gotten their alarms working.

**Comment by ghost** [comment]
So what should i do?

**Comment by xbony2** [comment]
Idk. Do you wanna see if I missed something? @dmf444

**Comment by ghost** [comment]
For others: there's mod called [energy control](https://www.curseforge.com/minecraft/mc-mods/energy-control), it is same like word control but more updated and it works correctly.

**Comment by gatoborrachon** [comment]
it also has a lot of compat for other mods
