### ISSUE TITLE
Will there be 1.15.2 support?

### ISSUE THREAD

**Issue by NXTler** [World-Control-Team/World-Control#39]
Will there be 1.15.2 support at some point of this mod?

**Comment by xbony2** [comment]
Not likely

**Comment by nightmarezzx** [comment]
UnsubscribeVon meinem/meiner Galaxy gesendet
-------- Ursprüngliche Nachricht --------Von: Eric Schneider <notifications@github.com> Datum: 07.12.20  01:56  (GMT+01:00) An: World-Control-Team/World-Control <World-Control@noreply.github.com> Cc: Subscribed <subscribed@noreply.github.com> Betreff: Re: [World-Control-Team/World-Control] Will there be 1.15.2 support? (#39) 
Closed #39.
