### ISSUE TITLE
Is the mod dead?

### ISSUE THREAD

**Issue by ApertureDevelopment** [World-Control-Team/World-Control#7]
Just asking, cause it does not look like you are doing anything anymore on it.

Without screens and the termometer blocks, this mod doesen't seem to be usefull anymore.

I know you might be busy with real life, so this is why I ask if you are going to do anything on it anymore.

We need stuff in 1.10.2 <.<

**Comment by xbony2** [comment]
Any content being added to 1.10.2 is extremely unlikely. That version is dead, modded development is focusing on 1.12 and if I was to work on this that's the version I'd focus on. Yes, I've been busy and whatnot. This is an open sourced project, and I'm willing to accept PRs from anyone who wants to help port it.
