### ISSUE TITLE
Rewrite Cards

### ISSUE THREAD

**Issue by adrwa** [World-Control-Team/World-Control#9]
I'd like to rewrite cards using a forge registry instead of a separate item to save on ID space and allowing addons to easily make new cards

Cards:
- [ ] Time
- [ ] Text
- [ ] EU
- [ ] EU Reactor
- [ ] FE
- [ ] ER Reactor

**Comment by dmf444** [comment]
1.14.+ doesn't care about ID space, and I don't plan to do this anymore.
